version: "3"
services:
  slack-thread-webhook:
    build: .
    image: slack-thread-webhook
    environment:
      REDIS_HOST: redis
    env_file: .env
    ports:
      - "3000:3000"
    links:
      - redis
    volumes:
      - .:/go/src/github.com/naoty/slack-thread-webhook
  redis:
    image: redis
