version: 2
jobs:
  test:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/naoty/slack-thread-webhook
    steps:
      - checkout
      - run:
          name: Notify workflow start
          command: |
            apk add bash curl
            .circleci/notify_workflow_start
      - run:
          name: Install dep
          command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Download packages
          command: dep ensure -vendor-only
      - run:
          name: Run tests
          command: go test
      - run:
          name: Notify finish
          command: .circleci/notify_job_finish
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t slack-thread-webhook .
      - deploy:
          name: Push image to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag slack-thread-webhook naoty/slack-thread-webhook
            docker push naoty/slack-thread-webhook
      - run:
          name: Notify finish
          command: |
            apk add bash curl
            .circleci/notify_job_finish
      - run:
          name: Notify workflow success
          command: |
            .circleci/notify_workflow_success
workflows:
  version: 2
  main:
    jobs:
      - test
      - build:
          requires:
            - test
