version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t naoty/slack-thread-webhook .
      - deploy:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push naoty/slack-thread-webhook
