version: 2
jobs:
  test:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/naoty/slack-thread-webhook
    steps:
      - checkout
      - run:
          name: Notify workflow start
          command: .circleci/notify_workflow_start
      - run:
          name: Install dep
          command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Download packages
          command: dep ensure -vendor-only
      - run:
          name: Run tests
          command: go test
      - run:
          name: Notify finish
          command: | 
            .circleci/notify_job_finish
            .circleci/notify_workflow_success
      - run:
          name: Notify failure
          when: on_fail
          command: |
            .circleci/notify_job_failed
            .circleci/notify_workflow_failed
workflows:
  version: 2
  main:
    jobs:
      - test
