version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t slack-thread-webhook .
      - deploy:
          name: Push image to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag slack-thread-webhook naoty/slack-thread-webhook
            docker push naoty/slack-thread-webhook
