#!/bin/bash -e

git_info=$(git log -1 --pretty="%an: %s")
sha1=$(git rev-parse --short HEAD)

cat << EOS | curl -X PUT -H "Content-Type: application/json" -d @- https://slack-thread-webhook.herokuapp.com/hooks/${CIRCLE_WORKFLOW_ID}
{
  "attachments": [
    {
      "color": "good",
      "title": "<https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|Success>",
      "text": "${git_info} (${sha1})",
      "footer": "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} | ${CIRCLE_BRANCH}"
    }
  ]
}
EOS
