#!/bin/bash -e

cat << EOS | curl -X POST -H "Content-Type: application/json" -d @- https://slack-thread-webhook.herokuapp.com/hooks/${CIRCLE_WORKFLOW_ID}
{
  "attachments": [
    {
      "color": "danger",
      "title": "Failed <${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>"
    }
  ]
}
EOS
