#!/bin/bash

cat << EOS | curl -X POST -H "Content-Type: application/json" -d @- https://slack-thread-webhook.herokuapp.com/hooks/${CIRCLE_WORKFLOW_ID}
{
  "attachments": [
    {
      "color": "good",
      "title": "Finish <${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>"
    }
  ]
}
EOS
