#!/bin/sh

cat << EOS | curl -X POST -H "Content-Type: application/json" https://slack-thread-webhook.herokuapp.com/hooks/${CIRCLE_BUILD_NUM}
{
  "attachments": [
    {
      "color": "#e3e4e6",
      "title": "Finish <${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>",
      "footer": "<${CIRCLE_REPOSITORY_URL}|${CIRCLE_PROJECT_REPONAME}> | ${CIRCLE_BRANCH}"
    }
  ]
}
EOS
